<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevGitAtom.Contracts\DevGitAtom.Contracts.csproj" />
    <ProjectReference Include="..\DevGitAtom.Engine\DevGitAtom.Engine.csproj" />
    <ProjectReference Include="..\DevGitAtom.GitAtoms\DevGitAtom.GitAtoms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\terminal.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup><Resource Include="Assets\logo.jpg" /></ItemGroup></Project>
