<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevGitAtom.Contracts\DevGitAtom.Contracts.csproj" />
    <ProjectReference Include="..\DevGitAtom.Engine\DevGitAtom.Engine.csproj" />
    <ProjectReference Include="..\DevGitAtom.GitAtoms\DevGitAtom.GitAtoms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    
    <!-- Thông tin ứng dụng (Hiện trong Task Manager & Properties) -->
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Product>DevGitAtom</Product>
    <Company>NgHuynh</Company>
    <Description>Trợ lý ảo Git trực quan bằng kéo thả</Description>
    <Copyright>Copyright © 2026</Copyright>
    <!-- <ApplicationIcon>Assets\logo.ico</ApplicationIcon> -->
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\terminal.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.jpg" />
    <Resource Include="Assets\logo.ico" />
  </ItemGroup></Project>
